remote_theme : mmistakes/minimal-mistakes
url                      : "https://alinghi.github.io" 
baseurl                  : "" 
minimal_mistakes_skin    : "mint"
locale                   : "en-US"
title                    : "Andy's Tech Blog"
title_separator          : "-"
name                     : "YunSeok[Andy] Na"
description              : "Math Blog"
repository               : "alinghi/alinghi.github.io"
